import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { describe, it } from "node:test";

describe("frontier public UI", () => {
  it("exposes the frontier handoff protocol without overclaiming record ownership", async () => {
    const html = await readFile("public/index.html", "utf8");

    assert.match(html, /Make businesses safely callable by AI agents/);
    assert.match(html, /readiness layer between AI agents and real-world businesses/);
    assert.match(html, /operating path the business already trusts/);
    assert.match(html, /owner-approved facts/);
    assert.match(html, /Gateway discovery contract/);
    assert.match(html, /Gateway-gated action/);
    assert.match(html, /Resolve the Pactway gateway first/);
    assert.match(html, /gateway check required/);
    assert.match(html, /Check capability before consent/);
    assert.match(html, /A request-only path cannot be shown as a confirmed outcome/);
    assert.match(html, /Pactway performs no state-changing action unless the user approves this copy/);
    assert.match(html, /gateway reported outcome/);
    assert.match(html, /the gateway returns status and receipt refs/i);
    assert.match(html, /Approval request flow/);
    assert.match(html, /From customer intent to an approved business request/);
    assert.match(html, /A customer tells an agent what they want/);
    assert.match(html, /verified gateway path to check current business facts/);
    assert.match(html, /starts from the customer's request/);
    assert.match(html, /scraped listings or model memory/);
    assert.match(html, /caps the action to what can honestly happen/);
    assert.match(html, /what will be sent, who receives it, and what outcome is being requested/);
    assert.match(html, /routes only the approved request/);
    assert.match(html, /Business system of record/);
    assert.match(html, /Record owner/);
    assert.match(html, /exact consent/);
    assert.match(html, /receipt proof/);
    assert.match(html, /What Pactway owns, and what it does not/);
    assert.match(html, /Pactway contract/);
    assert.match(html, /Readiness check/);
    assert.match(html, /Consent gate/);
    assert.match(html, /Pactway as system of record/);
    assert.match(html, /Current truth before display/);
    assert.match(html, /Honest capability/);
    assert.match(html, /not another booking system/);
    assert.match(html, /confirm \| request \| inform \| handoff/);
    assert.match(html, /"agentportOwnsRecord": false/);
    assert.match(html, /No consent means no state-changing action/);
    assert.match(html, /Pactway fronts existing systems without becoming the record/);
    assert.match(html, /Readiness gateway/);
    assert.match(html, /\/healthz/);
    assert.match(html, /\/\.well-known\/agentport\.json/);
    assert.match(html, /\/mcp/);
    assert.match(html, /\/actions\/resolve-ticket/);
    assert.match(html, /\/actions\/verify-ticket/);
    assert.match(html, /\/actions\/get-ticket-status/);
    assert.match(html, /\/actions\/get-allowed-ticket-actions/);
    assert.match(html, /\/actions\/send-ticket/);
    assert.match(html, /<meta name="description"/);
    assert.match(html, /<details class="mobile-menu">/);
    assert.match(html, /Gateway<\/a>/);
    assert.match(html, /prefers-reduced-motion: reduce/);

    assert.doesNotMatch(html, /Pactway owns booking\/POS truth/i);
    assert.doesNotMatch(html, /Pactway is the system of record/i);
    assert.doesNotMatch(html, /livePilotOk": true/);
    assert.doesNotMatch(html, /production wallet registry/i);
    assert.doesNotMatch(html, /real-business proof/i);
    assert.doesNotMatch(html, /Frontier plugin protocol/);
    assert.doesNotMatch(html, /salon, clinic, repair shop, restaurant/i);
    assert.doesNotMatch(html, /Square, Calendly, phone, email, forms, or an inbox/);
    assert.doesNotMatch(html, /agent-ready business profile/i);
    assert.doesNotMatch(html, /Agent-callable profile/);
    assert.doesNotMatch(html, /Business-safe action/);
    assert.doesNotMatch(html, /Pactway stores a safe reference/);
    assert.doesNotMatch(html, /Readiness resolves before consent/);
    assert.doesNotMatch(html, /verified current outcome/);
    assert.doesNotMatch(html, /From customer intent to the business's existing backend/);
    assert.doesNotMatch(html, /discover the ready profile/);
    assert.doesNotMatch(html, /current readiness tier/);
    assert.doesNotMatch(html, /Agent-ready flow/);
    assert.doesNotMatch(html, /Gateway action flow/);
    assert.doesNotMatch(html, /From agent intent to an approved business request/);
    assert.doesNotMatch(html, /Scroll-linked preview/);
    assert.doesNotMatch(html, /Business backend/);
    assert.doesNotMatch(html, /existing backend/);
    assert.doesNotMatch(html, /tabler-icons\.min\.css/);
  });
});
